version: '3.9'
services:
  board-database:
    image: mongo
    ports:
      - '27017:27017'
  board-backend:
    build: backend/
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://board-database:27017/blog
    ports:
      - '3000:3000'
    depends_on:
      - board-database
  board-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: https://vigilant-goggles-xgg9gppqppghvxx9-3000.app.github.dev/api/v1
    ports:
      - '3000:80'
    depends_on:
      - board-backend
